apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: nginx
          image: tejirih/my-app:latest
          ports:
            - containerPort: 80
          env:
            - name: SITE_NAME
              valueFrom:
                configMapKeyRef:
                  name: site-config
                  key: SITE_NAME
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: site-secret
                  key: SECRET_KEY